/**
 * 07-emit — write the final data/characters.ts and data/validation-report.md
 */
import { writeFile } from "fs/promises";
import { banner, log, readJson } from "./lib/util";
import type { InvincibleCharacter } from "../lib/types";

function tsLiteral(v: unknown, indent = 0): string {
  if (v === null) return "null";
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return "[]";
    return "[" + v.map((x) => tsLiteral(x, indent)).join(", ") + "]";
  }
  if (typeof v === "object") {
    const pad = " ".repeat(indent + 2);
    const lines = Object.entries(v as Record<string, unknown>).map(
      ([k, val]) => `${pad}${JSON.stringify(k)}: ${tsLiteral(val, indent + 2)}`,
    );
    return "{\n" + lines.join(",\n") + "\n" + " ".repeat(indent) + "}";
  }
  return "null";
}

async function main() {
  banner("Phase 07 — Emit");
  const records = await readJson<InvincibleCharacter[]>("scripts/data/05-enriched.json");
  const validation = await readJson<{
    errors: string[];
    warnings: string[];
    alignmentCounts: { a: string; n: number }[];
    speciesCounts: { s: string; n: number }[];
    canonCounts: { prime_s1_s4: number; post_s4_comic_spoiler: number; unknown_review: number };
  }>("scripts/data/06-validation.json");

  const header = `// AUTO-GENERATED by scripts/07-emit.ts — do not edit by hand.
// Run: npx tsx scripts/01-discover.ts && ... && npx tsx scripts/07-emit.ts
// Source: Invincible Fandom Wikis (CC BY-SA 3.0). Unofficial fan project.
import type { InvincibleCharacter } from "@/lib/types";

export const SOURCES_ATTRIBUTION =
  "Character data sourced from the Invincible Fandom Wikis (amazon-invincible.fandom.com, comic-invincible.fandom.com) under CC BY-SA 3.0. Invincible and all related characters, names, and likenesses are trademarks and copyrights of Robert Kirkman, Skybound Entertainment, Image Comics, and Amazon MGM Studios. This site is an unofficial fan project, not affiliated with or endorsed by any rights holder.";

`;

  const arrayLiteral =
    "export const characters: InvincibleCharacter[] = [\n" +
    records
      .map((r) => {
        const obj: InvincibleCharacter = {
          id: r.id,
          name: r.name,
          fullName: r.fullName,
          aliases: r.aliases,
          gender: r.gender,
          species: [...r.species].sort() as typeof r.species,
          alignment: r.alignment,
          affiliation: [...r.affiliation].sort() as typeof r.affiliation,
          powerType: [...r.powerType].sort() as typeof r.powerType,
          origin: r.origin,
          status: r.status,
          firstAppearanceSeason: r.firstAppearanceSeason,
          quotes: r.quotes,
          emojis: r.emojis,
          powerDescription: r.powerDescription,
          portraitUrl: r.portraitUrl,
          tier: r.tier,
          canonVisibility: r.canonVisibility,
          safeForNormalModes: r.safeForNormalModes,
          difficulty: r.difficulty,
          spoilerWarning: r.spoilerWarning ?? null,
          sources: r.sources,
          _needs_review: r._needs_review,
          _reviewNotes: r._reviewNotes,
        };
        return "  " + tsLiteral(obj, 2) + ",";
      })
      .join("\n") +
    "\n];\n\nexport const characterById: Record<string, InvincibleCharacter> =\n  Object.fromEntries(characters.map((c) => [c.id, c]));\n";

  await writeFile("data/characters.ts", header + arrayLiteral, "utf8");

  const report = [
    "# Invincibledle — Validation Report",
    "",
    `Generated: ${new Date().toISOString()}`,
    "",
    `**Total records:** ${records.length}`,
    `**Errors:** ${validation.errors.length}`,
    `**Warnings:** ${validation.warnings.length}`,
    "",
    "## Alignment distribution",
    "",
    ...validation.alignmentCounts.map((c) => `- ${c.a}: ${c.n}`),
    "",
    "## Species distribution",
    "",
    ...validation.speciesCounts.map((c) => `- ${c.s}: ${c.n}`),
    "",
    "## Canon visibility",
    "",
    `- S4-safe (normal modes): **${validation.canonCounts.prime_s1_s4}**`,
    `- Post-S4 comic spoiler (Deep-Cut only): **${validation.canonCounts.post_s4_comic_spoiler}**`,
    `- Unknown / needs review: **${validation.canonCounts.unknown_review}**`,
    "",
    "## Difficulty distribution",
    "",
    ...(["easy", "medium", "hard", "review"] as const).map(
      (d) => `- ${d}: **${records.filter((r) => r.difficulty === d).length}**`,
    ),
    "",
    "## Records flagged for canon review",
    "",
    ...(() => {
      const items = records
        .filter((r) => r.canonVisibility === "unknown_review")
        .map((r) => `- \`${r.id}\` — ${r.name} (${r.tier})`);
      return items.length === 0 ? ["_none_"] : items;
    })(),
    "",
    "## Records needing review",
    "",
    ...records
      .filter((r) => r._needs_review)
      .map((r) => `- \`${r.id}\` — ${r._reviewNotes ?? "enriched fields need human sign-off"}`),
    "",
    "## Warnings",
    "",
    ...(validation.warnings.length === 0 ? ["_none_"] : validation.warnings.map((w) => `- ${w}`)),
    "",
  ].join("\n");

  await writeFile("data/validation-report.md", report, "utf8");

  log("07", `wrote data/characters.ts (${records.length} records)`);
  log("07", `wrote data/validation-report.md`);
  console.log("\n── SUMMARY ──");
  console.log(`  characters: ${records.length}`);
  console.log(`  validation errors: ${validation.errors.length}`);
  console.log(`  validation warnings: ${validation.warnings.length}`);
  console.log(`  records needing review: ${records.filter((r) => r._needs_review).length}`);
  console.log(`  estimated human review time: ${Math.ceil((records.length * 6) / 60)} hours`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
